/**
 * Lantern riddle question bank.
 * Each item: { questionEn, questionZh, answer, explanationEn?, explanationZh? }
 * answer: string or array of accepted answers (first is canonical).
 */

const RIDDLES = [
  {
    questionEn: "What has a head and a tail but no body?",
    questionZh: "有頭有尾，冇身。打一動物。",
    answer: ["fish", "魚"],
    explanationEn: "Fish has a head (頭) and tail (尾) but we say it has no 'body' in the riddle sense.",
    explanationZh: "魚有頭有尾，謎面用「冇身」諧音「冇鱔」，指魚。",
  },
  {
    questionEn: "Half visible, half hidden. (One word, thing.)",
    questionZh: "半露半藏。打一物。",
    answer: ["moon", "月"],
    explanationEn: "The moon is half visible when half-illuminated, half hidden in shadow.",
    explanationZh: "月有半圓半缺，半露半藏。",
  },
  {
    questionEn: "A little house full of meat, no door to enter, no window to peek. (Food.)",
    questionZh: "一間小屋載滿肉，冇門入，冇窗睇。打一食物。",
    answer: ["egg", "蛋"],
    explanationEn: "Egg: shell is the 'house', inside is the 'meat', no door or window.",
    explanationZh: "蛋：殼係屋，裏面係「肉」，冇門冇窗。",
  },
  {
    questionEn: "Green hat, white body, stand in the mud all day. (Vegetable.)",
    questionZh: "綠帽白衣，成日企喺泥度。打一蔬菜。",
    answer: ["radish", "蘿蔔", "白蘿蔔"],
    explanationEn: "Radish: green leaves (hat), white root (body), grows in soil.",
    explanationZh: "蘿蔔：綠葉如帽，白根如身，長在泥中。",
  },
  {
    questionEn: "Red coat, white belly, black seeds inside. (Fruit.)",
    questionZh: "紅袍白肚，裏面黑子。打一水果。",
    answer: ["watermelon", "西瓜"],
    explanationEn: "Watermelon: red flesh when ripe, white near rind, black seeds.",
    explanationZh: "西瓜：紅肉白邊，黑子。",
  },
  {
    questionEn: "What gets wetter the more it dries?",
    questionZh: "越乾越濕。打一物。",
    answer: ["towel", "毛巾"],
    explanationEn: "A towel 'dries' you—the more you use it to dry, the wetter the towel gets.",
    explanationZh: "毛巾用來抹乾身，越抹越濕。",
  },
  {
    questionEn: "I have cities but no houses, forests but no trees, water but no fish. What am I?",
    questionZh: "有城冇屋，有林冇樹，有水冇魚。打一物。",
    answer: ["map", "地圖"],
    explanationEn: "A map has names of cities, forests, and waters but they are not real.",
    explanationZh: "地圖上有城名、林名、水名，但都唔係真嘅。",
  },
  {
    questionEn: "What word becomes shorter when you add two letters?",
    questionZh: "加兩個字就變短嘅係咩字？",
    answer: ["short", "short"],
    explanationEn: "Adding 'er' to 'short' makes 'shorter'—the word 'short' is now 'shorter' (longer word but meaning 'short' is still there). Actually: 'short' + 'er' = shorter (the concept 'short' gets 'shorter' in a play on words). Common answer: 'short'.",
    explanationZh: "「short」加「er」變「shorter」，意思係「更短」。",
  },
  {
    questionEn: "What comes once in a minute, twice in a moment, but never in a thousand years?",
    questionZh: "minute 裏有一次，moment 裏有兩次，一千 year 裏冇。係咩英文字母？",
    answer: ["m", "M"],
    explanationEn: "The letter 'm' appears once in 'minute', twice in 'moment', zero in 'thousand years'.",
    explanationZh: "英文字母 m：minute 有一個 m，moment 有兩個 m，thousand years 冇 m。",
  },
  {
    questionEn: "What has hands but cannot clap?",
    questionZh: "有手但唔會拍手。打一物。",
    answer: ["clock", "鐘"],
    explanationEn: "A clock has hands (hour and minute hands) but cannot clap.",
    explanationZh: "鐘有針（手），但唔會拍手。",
  },
  {
    questionEn: "What has a face and two hands but no arms or legs?",
    questionZh: "有面有兩隻手，冇手臂冇腳。打一物。",
    answer: ["clock", "鐘"],
    explanationEn: "Clock: face (dial), two hands (hour, minute), no arms or legs.",
    explanationZh: "鐘：有面（錶面）、兩根針（手），冇手腳。",
  },
  {
    questionEn: "What goes up but never comes down?",
    questionZh: "只會上，唔會落。打一物。",
    answer: ["age", "年齡", "年紀"],
    explanationEn: "Your age goes up and never comes down.",
    explanationZh: "年齡只會增加，唔會減少。",
  },
  {
    questionEn: "What is full of holes but still holds water?",
    questionZh: "好多窿，但裝到水。打一物。",
    answer: ["sponge", "海綿", "綿"],
    explanationEn: "A sponge has many holes but absorbs and holds water.",
    explanationZh: "海綿有好多孔，可以吸水儲水。",
  },
  {
    questionEn: "What word has five letters and sounds like it has only one?",
    questionZh: "五個字母，讀出嚟似得一個音。打一英文字。",
    answer: ["queue", "queue"],
    explanationEn: "'Queue' has five letters but is pronounced like 'Q' (one sound).",
    explanationZh: "queue 五個字母，讀音同 Q 一樣。",
  },
  {
    questionEn: "I speak without a mouth and hear without ears. I have no body but come alive with wind. What am I?",
    questionZh: "冇口會講，冇耳會聽，冇身，有風就活。打一自然現象。",
    answer: ["echo", "回聲"],
    explanationEn: "An echo 'speaks' (repeats) and 'hears' (reflects sound), no body, needs sound (like wind carrying it).",
    explanationZh: "回聲：重複你嘅聲音，好似會聽會講，有風/聲先有。",
  },
  {
    questionEn: "What can run but never walks, has a mouth but never talks?",
    questionZh: "會跑唔會行，有口唔會講。打一物。",
    answer: ["river", "河", "河流"],
    explanationEn: "A river 'runs' (flows), has a 'mouth' (river mouth), doesn't walk or talk.",
    explanationZh: "河會流（跑），有河口，唔會行唔會講。",
  },
  {
    questionEn: "What has legs but cannot walk?",
    questionZh: "有腳唔會行。打一物。",
    answer: ["table", "枱", "桌", "chair", "凳"],
    explanationEn: "Table (or chair) has legs but cannot walk.",
    explanationZh: "枱或凳有腳，唔會行。",
  },
  {
    questionEn: "What is always in front of you but cannot be seen?",
    questionZh: "永遠喺你前面，但睇唔到。打一物。",
    answer: ["future", "未來", "將來"],
    explanationEn: "The future is always 'ahead' but cannot be seen.",
    explanationZh: "未來永遠在前方，但睇唔見。",
  },
  {
    questionEn: "What breaks yet never falls, and what falls yet never breaks?",
    questionZh: "會碎唔會跌；會跌唔會碎。打兩樣嘢。",
    answer: ["day and night", "day night", "day, night", "晝夜", "日與夜"],
    explanationEn: "Day 'breaks' (dawn) but doesn't fall; night 'falls' but doesn't break.",
    explanationZh: "日破曉（break）唔會跌；夜降臨（fall）唔會碎。",
  },
  {
    questionEn: "What has a neck but no head?",
    questionZh: "有頸冇頭。打一物。",
    answer: ["bottle", "樽", "瓶"],
    explanationEn: "A bottle has a neck (the narrow part) but no head.",
    explanationZh: "樽有樽頸，冇頭。",
  },
  {
    questionEn: "What can you catch but not throw?",
    questionZh: "捉得到，掟唔到。打一物。",
    answer: ["cold", "感冒", "傷風"],
    explanationEn: "You catch a cold but don't throw it.",
    explanationZh: "會「染」到感冒，唔會「掟」感冒。",
  },
  {
    questionEn: "What has teeth but cannot eat?",
    questionZh: "有牙唔會食嘢。打一物。",
    answer: ["comb", "梳"],
    explanationEn: "A comb has teeth but cannot eat.",
    explanationZh: "梳有齒（牙），唔會食嘢。",
  },
  {
    questionEn: "What has one eye but cannot see?",
    questionZh: "有一隻眼但睇唔到。打一物。",
    answer: ["needle", "針"],
    explanationEn: "A needle has an eye (the hole) but cannot see.",
    explanationZh: "針有針眼，但睇唔到。",
  },
  {
    questionEn: "What is so fragile that saying its name breaks it?",
    questionZh: "一講個名就碎。打一物。",
    answer: ["silence", "沉默", "靜"],
    explanationEn: "Silence is broken when you speak (say anything, including 'silence').",
    explanationZh: "沉默一被講出就「破」咗。",
  },
  {
    questionEn: "What goes around the world but stays in a corner?",
    questionZh: "環遊世界但留喺角落。打一物。",
    answer: ["stamp", "郵票"],
    explanationEn: "A stamp travels the world on mail but stays in the corner of an envelope.",
    explanationZh: "郵票跟住信環遊世界，但永遠喺信封角落。",
  },
];
